{"name": "test_less_than_5[8]", "status": "failed", "statusDetails": {"message": "AssertionError: given number is not less than 5\nassert False", "trace": "data = 8\n\n    @pytest.mark.parametrize(\"data\", [8,5,6,3])\n    def test_less_than_5(data):\n        if data<5:\n            assert True\n        else:\n>           assert False, \"given number is not less than 5\"\nE           AssertionError: given number is not less than 5\nE           assert False\n\ntest_multiplication.py:27: AssertionError"}, "parameters": [{"name": "data", "value": "8"}], "start": 1670926238097, "stop": 1670926238097, "uuid": "23258870-9e77-471b-b7de-247293b40596", "historyId": "b4d19d72e32cb90b4f31e299efa88da0", "testCaseId": "bff07a8edb5163779e72e449c23ae71b", "fullName": "test_multiplication#test_less_than_5", "labels": [{"name": "suite", "value": "test_multiplication"}, {"name": "host", "value": "DESKTOP-D9P5RJB"}, {"name": "thread", "value": "13904-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_multiplication"}]}