{"name": "test_multiplication_11[3-35]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (11 * 3) == 35", "trace": "num = 3, output = 35\n\n    @pytest.mark.parametrize(\"num, output\", [(1, 11), (2, 22), (3, 35), (4, 44), (5,55)])\n    def test_multiplication_11(num, output):\n>       assert 11*num == output\nE       assert (11 * 3) == 35\n\ntest_multiplication.py:7: AssertionError"}, "parameters": [{"name": "num", "value": "3"}, {"name": "output", "value": "35"}], "start": 1670926237901, "stop": 1670926237904, "uuid": "7d3569b4-bff0-4f32-a4b1-a587dbb3ee05", "historyId": "7de3c40574d6072112491f672a815b3a", "testCaseId": "fbb3b3939d9b6ef572eb6dad4a8d6884", "fullName": "test_multiplication#test_multiplication_11", "labels": [{"name": "suite", "value": "test_multiplication"}, {"name": "host", "value": "DESKTOP-D9P5RJB"}, {"name": "thread", "value": "13904-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_multiplication"}]}