{"name": "test_val[6*9-42]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 54 == 42\n +  where 54 = eval('6*9')", "trace": "test_input = '6*9', expected = 42\n\n    @pytest.mark.parametrize(\"test_input,expected\", [(\"3+5\", 8), (\"2+4\", 6), (\"6*9\", 42)])\n    def test_val(test_input, expected):\n>       assert eval(test_input) == expected\nE       AssertionError: assert 54 == 42\nE        +  where 54 = eval('6*9')\n\ntest_multiplication.py:12: AssertionError"}, "parameters": [{"name": "test_input", "value": "'6*9'"}, {"name": "expected", "value": "42"}], "start": 1670925497096, "stop": 1670925497097, "uuid": "16152fe9-3550-4deb-82dc-81b0ee579afb", "historyId": "1de621dccf3c2edab3f34331cc8e673e", "testCaseId": "3e579d8a87f83f8f040108dd12e17d9a", "fullName": "test_multiplication#test_val", "labels": [{"name": "suite", "value": "test_multiplication"}, {"name": "host", "value": "DESKTOP-D9P5RJB"}, {"name": "thread", "value": "6700-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_multiplication"}]}