{"name": "test_less_than_5[5]", "status": "failed", "statusDetails": {"message": "AssertionError: given number is not less than 5\nassert False", "trace": "data = 5\n\n    @pytest.mark.parametrize(\"data\", [8,5,6,3])\n    def test_less_than_5(data):\n        if data<5:\n            assert True\n        else:\n>           assert False, \"given number is not less than 5\"\nE           AssertionError: given number is not less than 5\nE           assert False\n\ntest_multiplication.py:27: AssertionError"}, "parameters": [{"name": "data", "value": "5"}], "start": 1670926238108, "stop": 1670926238109, "uuid": "5269f7f4-7019-4879-bae6-2751f364b4e8", "historyId": "09b02fc31b17b7aff7b3c4d8226f3728", "testCaseId": "bff07a8edb5163779e72e449c23ae71b", "fullName": "test_multiplication#test_less_than_5", "labels": [{"name": "suite", "value": "test_multiplication"}, {"name": "host", "value": "DESKTOP-D9P5RJB"}, {"name": "thread", "value": "13904-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_multiplication"}]}